spring:
  datasource:
    url: jdbc:mysql://localhost:3306/searchstudy?serverTimeZone=UTC&characterEncoding=UTF8
    username: searchstudy
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  devtools:
    livereload:
      enabled: true

